### ISSUE TITLE
The original resource?

### ISSUE THREAD

**Issue by yadamit** [Mayurji/MLWithPytorch#2]
Hey, great job.
I am wondering what's the actual resource for this 30daysofML? Or 100daysofML. Could you share the link?
Thanks

**Comment by Mayurji** [comment]
There is nothing like actual source. Yes, I did follow many github repos like ML-from-scratch, sklearn Library, ML cheatsheet. etc.
one of the links here: https://ml-cheatsheet.readthedocs.io/
