### ISSUE TITLE
can improve folder structure by prefixing 0 for day 1-9

### ISSUE THREAD

**Issue by rohitkuk** [Mayurji/MLWithPytorch#3]
See this :: https://github.com/rohitkuk/MLWithPytorch

**Comment by rrrokhtar** [comment]
Much more better. I think you can make pull request for that instead and mention the owner right there

**Comment by rohitkuk** [comment]
doesn't allow pull request.

**Comment by Mayurji** [comment]
@rohitkuk, I've updated the folder names. Thanks for the suggestion.
